### ISSUE TITLE
Issues when running on Windows

### ISSUE THREAD

**Issue by MarceloSalazar** [maclobdell/simple_mbed_test_runner#1]
@maclobdell I've tried version 28374ec0061829a44b32bb9226b744b68e486217

The current version is using `sudo`. This obviously doesn't work on Windows, but we should also consider removing it to run on Linux with user context.

**Comment by maclobdell** [comment]
fixed with this commit 7568b3c1f0981f2eb4147f4707af5bb98e7d9807
