### ISSUE TITLE
execute greentea commands directly instead of 'mbed test'

### ISSUE THREAD

**Issue by maclobdell** [maclobdell/simple_mbed_test_runner#4]
needs exploration.  perhaps it would be more reliable and stable to to import greentea python module and run tests that way.

**Comment by MarceloSalazar** [comment]
I'd suggest sticking to Mbed CLI. This would let us verify the integration of the tools and ensure others can use a single command (mbed test...) to prepare the environment and run tests.

**Comment by maclobdell** [comment]
closing.  seems no reason to change the way it is working now.
